version: '3.8'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg16
    container_name: sumatosensa_db
    environment: 
      POSTGRES_DB: ${POSTGRES_DB:-sumatosensa}
      POSTGRES_USER: ${POSTGRES_USER:-sumatosensa_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-sumatosensa_password}
      TIMESCALEDB_TELEMETRY: "off"
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/01-init.sql
    ports:
      - "5432:5432"
    networks:
      - sumatosensa_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-sumatosensa_user} -d ${POSTGRES_DB:-sumatosensa}"]
      interval: 30s
      timeout: 10s
      retries: 3

  mosquitto:
    build: ./mqtt
    container_name: sumatosensa_mqtt
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_logs:/mosquitto/log
      - ./mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - sumatosensa_network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    container_name: sumatosensa_backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER:-sumatosensa_user}:${POSTGRES_PASSWORD:-sumatosensa_password}@sumatosensa_db:5432/${POSTGRES_DB:-sumatosensa}
      MQTT_BROKER_HOST: sumatosensa_mqtt
      MQTT_BROKER_PORT: 1883
      SECRET_KEY: ${JWT_SECRET_KEY:-your-super-secret-jwt-key-change-this-in-production}
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_HOURS: 8
      PORT: 8000
    volumes:
      - ./backend:/app
      - backend_reports:/app/reports
    depends_on:
      timescaledb:
        condition: service_healthy
      mosquitto:
        condition: service_started
    networks:
      - sumatosensa_network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        CACHE_BUSTER: ${CACHE_BUSTER:-1}
    container_name: sumatosensa_frontend
    environment:
      VITE_API_URL: ${VITE_API_URL:-http://localhost:8000}
      VITE_WS_URL: ${VITE_WS_URL:-ws://localhost:8000/ws}
      PORT: 80
    ports:
      - 80:80
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - sumatosensa_network
    restart: unless-stopped


volumes:
  timescaledb_data:
  mosquitto_data:
  mosquitto_logs:
  backend_reports:

networks:
  sumatosensa_network:
    driver: bridge